### ISSUE TITLE
synchronize

### ISSUE THREAD

**Issue by lixa4ev** [Whitecoin-XWC/Whitecoin-core#1]
I can’t synchronize the old XWC wallet, there are no seeds to exchange the remaining old coins XWC. What can I do?

**Comment by urcoder-9527** [comment]
please download new XWC wallet from here:
* new XWC wallet: https://github.com/Whitecoin-XWC/Whitecoin-qt/releases/tag/1.2.7
* exchange notice: https://www.whitecoin.info/newsDetails?id=89

**Comment by urcoder-9527** [comment]
@lixa4ev , Please according to above information to exchange your old coins XWC.

**Comment by willxwc** [comment]
you can add the node manually:  
addnode 47.112.42.140:15814 onetry→Enter

addnode 47.112.42.140:15814 add →Enter


218.93.206.2:15814 | /Satoshi:2.5.1/
91.121.110.119:15814 | /dVhitecoin:2.5.21
47.112.42.140:15814 | /Satoshi:2.5.1/
69.132.81.225:15814 | /Satoshi:2.5.1/
2.82.239.33:15814 | /Whitecoin:2.5.2/
47.74.4.101:15814 | /Satoshi:2.5.1/
24.251.224.32:15814 | /Satoshi:2.5.1/
126.82.148.100:15814 | /Satoshi:2.5.1/
47.244.155.116:15814 | /Whitecoin:2.5.3/

if you have any problem ,you can email: info@whitecoin.info
