### ISSUE TITLE
I am trying to build node with the master tag,but build is failing

### ISSUE THREAD

**Issue by Alpanca** [Whitecoin-XWC/Whitecoin-core#2]
file(GLOB HEADERS "include/graphene/wallet/*.hpp")
find_package( Perl )
find_package( Doxygen )
  # no perl and doxygen, generate the best docs we can at runtime from reflection
  add_custom_command( OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/api_documentation.cpp
                      COMMAND ${CMAKE_COMMAND} -E copy_if_different ${CMAKE_CURRENT_SOURCE_DIR}/api_documentation_standin.cpp ${CMAKE_CURRENT_BINARY_DIR}/api_documentation.cpp
                      DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/api_documentation_standin.cpp )
add_library( graphene_wallet wallet.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../chain/contract_entry.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../chain/protocol/memo.cpp ${CMAKE_CURRENT_BINARY_DIR}/api_documentation.cpp ${HEADERS} )
target_link_libraries( graphene_wallet PRIVATE graphene_app graphene_net graphene_chain uvm graphene_utilities fc ${CMAKE_DL_LIBS} ${PLATFORM_SPECIFIC_LIBS} )
target_include_directories( graphene_db PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include" )
if(MSVC)
  set_source_files_properties( wallet.cpp PROPERTIES COMPILE_FLAGS "/bigobj" )
endif(MSVC)
install( TARGETS
   graphene_wallet
   RUNTIME DESTINATION bin
   LIBRARY DESTINATION lib
   ARCHIVE DESTINATION lib
)
install( FILES ${HEADERS} DESTINATION "include/graphene/wallet" )

#### Error as following:
```
[ 90%] Linking CXX executable embed_genesis
../uvm/libuvm.a(loslib.cpp.o): In function `os_tmpname(lua_State*)':
loslib.cpp:(.text+0x2b0): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
../wallet/libgraphene_wallet.a(api_documentation.cpp.o): In function `void fc::raw::pack<fc::datastream<unsigned long>, graphene::chain::fee_schedule>(fc::datastream<unsigned long>&, fc::smart_ref<graphene::chain::fee_schedule> const&)':
api_documentation.cpp:(.text._ZN2fc3raw4packINS_10datastreamImEEN8graphene5chain12fee_scheduleEEEvRT_RKNS_9smart_refIT0_EE[_ZN2fc3raw4packINS_10datastreamImEEN8graphene5chain12fee_scheduleEEEvRT_RKNS_9smart_refIT0_EE]+0x1c): undefined reference to `fc::smart_ref<graphene::chain::fee_schedule>::operator*() const'
libraries/egenesis/CMakeFiles/embed_genesis.dir/build.make:154: recipe for target 'libraries/egenesis/embed_genesis' failed
collect2: error: ld returned 1 exit status
make[2]: *** [libraries/egenesis/embed_genesis] Error 1
make[1]: *** [libraries/egenesis/CMakeFiles/embed_genesis.dir/all] Error 2
CMakeFiles/Makefile2:435: recipe for target 'libraries/egenesis/CMakeFiles/embed_genesis.dir/all' failed
Makefile:129: recipe for target 'all' failed
```

**Comment by jaeik-kim** [comment]
Compile the whitecoin, we need some third-part library:
* [blocklink_crosschain_privatekey](https://github.com/BlockLink/blocklink_crosschain_privatekey)
* [eth_crosschain_privatekey](https://github.com/BlockLink/eth_crosschain_privatekey)
* [boost_1_63_0](https://boostorg.jfrog.io/artifactory/main/release/1.63.0/source/boost_1_63_0.tar.gz)
```shell
LDFLAGS=-no-pie ./bootstrap.sh
LDFLAGS=-no-pie ./b2
```

**Comment by jaeik-kim** [comment]
To simplify the compilation process, I will write a build.sh file for it.

**Comment by jaeik-kim** [comment]
#### ubuntu-18.04

Compile the whitecoin-xwc at ubuntu-18.04, please refer blow command line:

* update your compile machine

  ```shell
  $> sudo apt-get -f install
  $> sudo apt-get update
  ```

* install some required library

  ```shell
  $> sudo apt-get install cmake make libbz2-dev libdb++-dev libdb-dev libssl-dev openssl autoconf
  $> sudo apt-get install libreadline-dev --fix-missing
  $> sudo apt-get install g++
  ```

* build whitecoin-xwc now

  ```shell
  $> git clone --recursive git@github.com:Whitecoin-XWC/Whitecoin-core.git
  $> cd Whitecoin-core
  $> chmod +x build.sh
  $> ./build.sh
  
  #Please wait the compile....
  ```

* executable file `xwc_cli & xwc_node`

  > If the compile is success, you can found the executable files `xwc_cli & xwc_node` under the folder output.

**Comment by jaeik-kim** [comment]
#### self test
* test server's information
```
root@ubuntu:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

* compile the whitecoin-xwc according to [manual](https://github.com/Whitecoin-XWC/Whitecoin-core/issues/2#issuecomment-922419197)

**Comment by Whitecoin-Owner** [comment]
the task is completed.
